### ISSUE TITLE
Не поддерживается опция reportUnusedDisableDirectives

### ISSUE THREAD

**Issue by pongo** [eslintcc/eslintcc#17]
В конфиге eslint есть опция [reportUnusedDisableDirectives](https://eslint.org/docs/user-guide/configuring#report-unused-eslint-disable-comments).

eslintcc ее не принимает:
```
ESLint configuration in .eslintrc.js is invalid:
        - Unexpected top-level property "reportUnusedDisableDirectives".
```

пример .eslintrc.js:
```js
module.exports = {
  reportUnusedDisableDirectives: true,
  rules: {}
};
```

**Comment by IgorNovozhilov** [comment]
Похоже это была бага самого eslint, добавил тест на это, все работает:
https://travis-ci.com/eslintcc/eslintcc/builds/141866938
