### ISSUE TITLE
Cannot read property 'name' of null when processing anonymous class

### ISSUE THREAD

**Issue by groupsky** [eslintcc/eslintcc#19]
**Describe the bug**
An error message `Cannot read property 'name' of null` and termination with exit code 1 when processing a file with anonymous class

**To Reproduce**
1. Create a file `test.js` with content
```javascript
export default class {
  foo () {
  }
}
```
2. Run `eslintcc` on it
```shell
npx eslintcc test.js
```
3. See the error
```
Cannot read property 'name' of null
```

**Expected behavior**
Should not error and consider it anonymous class

**Comment by IgorNovozhilov** [comment]
@groupsky, fixed in eslintcc@0.5.4
